transporteur_homepage:
    path:     /
    defaults: { _controller: TransporteurBundle:Default:index }

ajouter_livraison:
    path: /ajouterLivraison
    defaults: {_controller: TransporteurBundle:Livraison:ajouterLivraison}

afficher_livraison_all:
    path: /afficherLivraison
    defaults: {_controller: TransporteurBundle:Livraison:getAllLivraison}

supprimer_livraison:
    path: /supprimerLivraison/{id}
    defaults: {_controller: TransporteurBundle:Livraison:supprimerLivraison}


aff_liv_Trans_NL:
    path: /AffLivTransNL
    defaults: {_controller: TransporteurBundle:Livraison:afficherLivraisonParTransporteurNonLivre}

aff_liv_Trans_L:
    path: /AffLivTransL
    defaults: {_controller: TransporteurBundle:Livraison:afficherLivraisonParTransporteurLivre}

modifier_livraison:
    path: /modifierLivraison/{id}
    defaults: {_controller: TransporteurBundle:Livraison:modifierEtatLivraison}


ajouter_contrat:
    path : /ajouterContrat
    defaults : {_controller: TransporteurBundle:Contrat:ajouterContrat}

afficher_contrat:
    path: /afficherContrat
    defaults: {_controller: TransporteurBundle:Contrat:afficherContratParPropE}







