stock_homepage:
    path:     /stk
    defaults: { _controller: StockBundle:Default:index }
stock_category:
    path:     /categories_index
    defaults: { _controller: StockBundle:Categories:index }
category_sho:
    path:     /categories_show
    defaults: { _controller: StockBundle:Categories:show }
category_sho1:
    path:     /categories_new
    defaults: { _controller: StockBundle:Categories:new }
categor_show2:
    path:     /categories_edit
    defaults: { _controller: StockBundle:Categories:edit }
categoy_show21:
    path:     /categories_delete
    defaults: { _controller: StockBundle:Categories:delete }
stock_homepag:
    path:     /produit_index
    defaults: { _controller: StockBundle:Produit:index }
category_show:
    path:     /produit_show
    defaults: { _controller: StockBundle:Produit:show }
category_show1:
    path:     /produit_new
    defaults: { _controller: StockBundle:Produit:new }
category_show2:
    path:     /produit_edit
    defaults: { _controller: StockBundle:Produit:edit }
ategory_show21:
    path:     /produit_delete
    defaults: { _controller: StockBundle:Produit:delete}
qategory_show21:
    path:     /qte
    defaults: { _controller: StockBundle:Produit:qte}
uqategory_show21:
    path:     /prix
    defaults: { _controller: StockBundle:Produit:prix}
pategory_show21:
    path:     /calcul
    defaults: { _controller: StockBundle:Produit:calculNbProd}
ategory_sh1:
    path:     /mouvementdustock_new
    defaults: { _controller: StockBundle:MouvementDuStock:new }
lategory_sh1:
    path:     /mouvementdustock_index
    defaults: { _controller: StockBundle:MouvementDuStock:index }
lategry_sh1:
    path:     /ajouter/{qte}/{fk}
    defaults: { _controller: StockBundle:MouvementDuStock:ajouterQuantite }
lategry_h1:
    path:     /check/{fk}
    defaults: { _controller: StockBundle:MouvementDuStock:check }
olategry_h1:
    path:     /mouvementdustock_delete
    defaults: { _controller: StockBundle:MouvementDuStock:delete }
polategry_h1:
    path:     /get
    defaults: { _controller: StockBundle:MouvementDuStock:get }
admin:
    path:     /user
    defaults: { _controller: StockBundle:Admin:user }
admin1:
    path:     /categ
    defaults: { _controller: StockBundle:Admin:index }
admin12:
    path:     /prod
    defaults: { _controller: StockBundle:Admin:produit }
admin123:
    path:     /statC
    defaults: { _controller: StockBundle:Admin:statC }
rcategory_sho:
    path:     /allC
    defaults: { _controller: StockBundle:Json:allC }
mrcategory_sho:
    path:     /allE
    defaults: { _controller: StockBundle:Json:allE }
prcategory_sho:
    path:     /allP
    defaults: { _controller: StockBundle:Json:allP }
pprcategory_sho:
    path:     /allM
    defaults: { _controller: StockBundle:Json:allM }
rfcategory_sho:
    path:     /newC
    defaults: { _controller: StockBundle:Json:ajouterC }
rpfcategory_sho:
    path:     /newP
    defaults: { _controller: StockBundle:Json:ajouterP }
mrpfcategory_sho:
    path:     /newM
    defaults: { _controller: StockBundle:Json:ajouterM }
pmrpfcategory_sho:
    path:     /modifP
    defaults: { _controller: StockBundle:Json:modifierP }
cpmrpfcategory_sho:
    path:     /modifC
    defaults: { _controller: StockBundle:Json:modifierC }
mcpmrpfcategory_sho:
    path:     /modifM
    defaults: { _controller: StockBundle:Json:modifierM }
qpmrpfcategory_sho:
    path:     /suppP
    defaults: { _controller: StockBundle:Json:deleteP }
qpmrpfcaptegory_sho:
    path:     /suppC
    defaults: { _controller: StockBundle:Json:deleteC }
mqpmrpfcaptegory_sho:
    path:     /suppM
    defaults: { _controller: StockBundle:Json:deleteM }
