stock_homepage:
    path:     /stk
    defaults: { _controller: StockBundle:Default:index }
stock_category:
    path:     /categories_index
    defaults: { _controller: StockBundle:Categories:index }
category_sho:
    path:     /categories_show
    defaults: { _controller: StockBundle:Categories:show }
category_sho1:
    path:     /categories_new
    defaults: { _controller: StockBundle:Categories:new }
categor_show2:
    path:     /categories_edit
    defaults: { _controller: StockBundle:Categories:edit }
categoy_show21:
    path:     /categories_delete
    defaults: { _controller: StockBundle:Categories:delete }
stock_homepag:
    path:     /produit_index
    defaults: { _controller: StockBundle:Produit:index }
category_show:
    path:     /produit_show
    defaults: { _controller: StockBundle:Produit:show }
category_show1:
    path:     /produit_new
    defaults: { _controller: StockBundle:Produit:new }
category_show2:
    path:     /produit_edit
    defaults: { _controller: StockBundle:Produit:edit }
ategory_show21:
    path:     /produit_deletee/{id}
    defaults: { _controller: StockBundle:Produit:deleteProd }
ategory_sh1:
    path:     /mouvementdustock_new
    defaults: { _controller: StockBundle:MouvementDuStock:new }
lategory_sh1:
    path:     /mouvementdustock_index
    defaults: { _controller: StockBundle:MouvementDuStock:index }
lategry_sh1:
    path:     /ajouter/{qte}/{fk}
    defaults: { _controller: StockBundle:MouvementDuStock:ajouterQuantite }
lategry_h1:
    path:     /check/{fk}
    defaults: { _controller: StockBundle:MouvementDuStock:check }
admin:
    path:     /user
    defaults: { _controller: StockBundle:Admin:user }
admin1:
    path:     /categ
    defaults: { _controller: StockBundle:Admin:index }
admin12:
    path:     /prod
    defaults: { _controller: StockBundle:Admin:produit }
