stock_homepage:
    path:     /stk
    defaults: { _controller: StockBundle:Default:index }
stock_category:
    path:     /categories_index
    defaults: { _controller: StockBundle:Categories:index }
category_show:
    path:     /categories_show
    defaults: { _controller: StockBundle:Categories:show }
category_show1:
    path:     /categories_new
    defaults: { _controller: StockBundle:Categories:new }
category_show2:
    path:     /categories_edit
    defaults: { _controller: StockBundle:Categories:edit }
category_show21:
    path:     /categories_delete
    defaults: { _controller: StockBundle:Categories:delete }
