imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@StockBundle/Resources/config/services.yml" }
    - { resource: "@GererEntrepotBundle/Resources/config/services.yml" }
    - { resource: "@TransporteurBundle/Resources/config/services.yml" }
    - { resource: "@CommandeBundle/Resources/config/services.yml" }
    - { resource: "@NotificationBundle/Resources/config/services.yml" }
    - { resource: "@RHBundle/Resources/config/services.yml" }
    - { resource: "@ForumBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    #
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    encryption: ssl
    port:    465
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
    spool: { type: memory }
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:                               # this lines
        mailer: fos_user.mailer.twig_swift # this lines
    from_email:
        address: "debbo.web@gmail.com"
        sender_name: "123"

sensio_framework_extra:
    router:
        annotations: false
vich_uploader:
    db_driver: orm

    mappings:
        produit:
            uri_prefix: /images/produits
            upload_destination: '%kernel.project_dir%/web/public/images/produits'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        categorie:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/web/public/images/categories'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        employees:
            uri_prefix: /images/employees
            upload_destination: '%kernel.project_dir%/web/images'

            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
gregwar_captcha: ~


knp_snappy:
     pdf:
         enabled:    true
         # If you have wkhtmltopdf as an environment variable you don't need to provide the
         # full path to the executable, use it in the same way as you use in the console
         #binary:  "wkhtmltopdf"
         binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
         options:
               no-outline: true
               page-size: LETTER
               # Recommended to set UTF-8 as default encoding :)
               encoding: UTF-8
     image:
         enabled:    true
         binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\""
         options:    []


# fos_user bundle:

#fos_user:
 #   db_driver: orm
 #   firewall_name: main
  #  user_class: AppBundle\Entity\User
   # service:
    #    mailer: fos_user.mailer.twig_swift
    #from_email:
     #   address: "mohamedfarouk.benakacha@esprit.tn"
      #  sender_name: "Farouk"

fos_message:
    db_driver: orm
    thread_class: ForumBundle\Entity\Thread
    message_class: ForumBundle\Entity\Message

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query parameter name
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
