gerer_entrepot_entrepot:
    resource: "@GererEntrepotBundle/Controller/EntrepotController.php"
    type:     annotation

gerer_entrepot_location:
    resource: "@GererEntrepotBundle/Controller/LocationController.php"
    type:     annotation

entrepot:
    resource: "@GererEntrepotBundle/Resources/config/routing.yml"
    prefix:   /entrepot


app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"