fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user
rh:
    resource: "@RHBundle/Resources/config/routing.yml"
    prefix:   /rh

entrepot:
    resource: "@EntrepotBundle/Resources/config/routing.yml"
    prefix:   /Entrepot


app:
    resource: '@AppBundle/Controller/'
    type: annotation
