stock_mouvement_du_stock:
    resource: "@StockBundle/Controller/MouvementDuStockController.php"
    type:     annotation

stock_produit:
    resource: "@StockBundle/Controller/ProduitController.php"
    type:     annotation

stock_categories:
    resource: "@StockBundle/Controller/CategoriesController.php"
    type:     annotation

stock:
    resource: "@StockBundle/Resources/config/routing.yml"
    prefix:   /Stock

entrepot:
    resource: "@EntrepotBundle/Resources/config/routing.yml"
    prefix:   /Entrepot
gerer_entrepot_entrepot:
    resource: "@GererEntrepotBundle/Controller/EntrepotController.php"
    type:     annotation

gerer_entrepot_location:
    resource: "@GererEntrepotBundle/Controller/LocationController.php"
    type:     annotation

gerer_entrepot_mobile:
    resource: "@GererEntrepotBundle/Controller/MobileEntrepotController.php"
    type:     annotation


app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

