transporteur:
    resource: "@TransporteurBundle/Resources/config/routing.yml"
    prefix:   /Transporteur

entrepot:
    resource: "@EntrepotBundle/Resources/config/routing.yml"
    prefix:   /Entrepot

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"