forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /message

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

entrepot:
    resource: "@EntrepotBundle/Resources/config/routing.yml"
    prefix:   /Entrepot

app:
    resource: '@AppBundle/Controller/'
    type: annotation



