notification_blog:
    resource: "@NotificationBundle/Controller/BlogController.php"
    type:     annotation

notification:
    resource: "@NotificationBundle/Resources/config/routing.yml"
    prefix:   annotation

commande_commande:
    resource: "@CommandeBundle/Controller/CommandeController.php"
    type:     annotation


app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


