notification_blog:
    resource: "@NotificationBundle/Controller/BlogController.php"
    type:     annotation

notification:
    resource: "@NotificationBundle/Resources/config/routing.yml"
    prefix:   /Notification


commande_commande:
    resource: "@CommandeBundle/Controller/CommandeController.php"
    type:     annotation

commande_json:
    resource: "@CommandeBundle/Controller/CommandeJsonController.php"
    type:     annotation

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


