stock_mouvement_du_stock:
    resource: "@StockBundle/Controller/MouvementDuStockController.php"
    type:     annotation

stock_produit:
    resource: "@StockBundle/Controller/ProduitController.php"
    type:     annotation

stock_categories:
    resource: "@StockBundle/Controller/CategoriesController.php"
    type:     annotation

stock:
    resource: "@StockBundle/Resources/config/routing.yml"
    prefix:   /Stock
transporteur:
    resource: "@TransporteurBundle/Resources/config/routing.yml"
    prefix:   /Transporteur

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user
rh:
    resource: "@RHBundle/Resources/config/routing.yml"
    prefix:   /rh

entrepot:
    resource: "@EntrepotBundle/Resources/config/routing.yml"
    prefix:   /Entrepot
gerer_entrepot_entrepot:
    resource: "@GererEntrepotBundle/Controller/EntrepotController.php"
    type:     annotation

gerer_entrepot_location:
    resource: "@GererEntrepotBundle/Controller/LocationController.php"
    type:     annotation

gerer_entrepot_mobile:
    resource: "@GererEntrepotBundle/Controller/MobileEntrepotController.php"
    type:     annotation

notification_blog:
    resource: "@NotificationBundle/Controller/BlogController.php"
    type:     annotation

notification:
    resource: "@NotificationBundle/Resources/config/routing.yml"
    prefix:   /Notification


commande_commande:
    resource: "@CommandeBundle/Controller/CommandeController.php"
    type:     annotation

commande_json:
    resource: "@CommandeBundle/Controller/CommandeJsonController.php"
    type:     annotation


app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


