security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_CLIENT: ROLE_USER
        ROLE_PROP: ROLE_USER
        ROLE_PROPRIETAIRE: ROLE_USER
        ROLE_TRANSPORTEUR: ROLE_USER
        ROLE_ENTREPOT: ROLE_USER
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~



    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                    #provider: fos_userbundle
                default_target_path: 'user_Check'
                remember_me: true
                # if you are using Symfony < 2.8, use the following config instead:
    # csrf_provider: form.csrf_provider
            logout: true
            anonymous: true
            # activate different ways to authenticate


      # activate different ways to authenticate

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/back, role: ROLE_ADMIN }
        - { path: ^/front, role: ROLE_USER }
        - { path: ^/frontF, role: ROLE_USER }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/entrepot/^, role: ROLE_PROPRIETAIRE }
        - { path: ^/location/^, role: ROLE_CLIENT }
        - { path: ^/commande/, role: ROLE_CLIENT }

