# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_CLIENT: ROLE_USER
        ROLE_PROP: ROLE_USER
        ROLE_PROPRIETAIRE: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login
                # if you are using Symfony < 2.8, use the following config instead:
    # csrf_provider: form.csrf_provider
            logout: true
            anonymous: true
            # activate different ways to authenticate

            logout: true
            anonymous: true


            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/back, role: ROLE_ADMIN }
        - { path: ^/front, role: ROLE_USER }
        - { path: ^/frontF, role: ROLE_USER }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/entrepot/^, role: ROLE_PROPRIETAIRE }
        - { path: ^/location/^, role: ROLE_CLIENT }
